#!/usr/bin/env bash

#vim
cp -R .vim* ~/.

if [ "$(uname)" == "Darwin" ]; then
    # Install homebrew
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    # Node
    brew update
    brew install node

    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

    # Hyper
    brew cask install hyper

    pushd ~/.hyper_plugins && npm i && popd
    cp .hyper.js ~/

elif [[ $(uname) =~ MINGW.* ]]; then
    pacman -S zsh
    pacman -S tmux
    powershell -Command "Start-Process PowerShell \"Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')) \" -Verb RunAs -Wait"

    rm -rf ~/.oh-my-zsh
    git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh

    # Hyper
    powershell -Command "Start-Process PowerShell \"choco install hyper\" -Verb RunAs -Wait"
    pushd ~/.hyper_plugins && npm i && popd
    cp .hyper-win.js ~/.hyper.js
fi

# zsh config
if [ "$(uname)" == "Darwin" ]; then
    cp .zshrc_mac ~/.zshrc
elif [ "$(uname)" =~ MING.* ]; then
    co .zshrc_windows ~/.zshrc
fi

# power-line fonts
if [[ $(uname) =~ MING.* ]]; then
    git clone https://github.com/powerline/fonts
    powershell -Command "Start-Process PowerShell \".\\fonts\\install.ps1\" -Verb RunAs -Wait -NoNewWindow"
    rm -rf fonts

# append bash helpers to .bashrc
cat .bash_helpers.sh >> ~/.bashrc

# tmux
cp .tmux.conf ~/
